CREATE OR REPLACE TABLE JOMUMA1.USUARIOS_SISTEMA FOR SYSTEM NAME USERS (
  ID DECIMAL(5, 0) NOT NULL GENERATED ALWAYS AS IDENTITY,
  NOMBRE CHAR(50) CCSID 1145 NOT NULL WITH DEFAULT,
  APELLIDOS CHAR(50) CCSID 1145 NOT NULL WITH DEFAULT,
  EMAIL CHAR(100) CCSID 1145 NOT NULL WITH DEFAULT,
  PASSWORD VARCHAR(128) FOR BIT DATA,     -- DE 128 Y FOR BIT DATA

  CONSTRAINT JOMUMA1.USERS_PK1 PRIMARY KEY(ID)
) RCDFMT RUSERS;

LABEL ON TABLE JOMUMA1.USUARIOS_SISTEMA IS 'USUARIOS DE UN SISTEMA FICTICIO - ENCRIPTADO'; 

LABEL ON COLUMN JOMUMA1.USUARIOS_SISTEMA ( 
  ID        IS 'ID',
  NOMBRE    IS 'NOMBRE DE USUARIO',
  APELLIDOS IS 'APELLIDOS DE USUARIO',
  EMAIL     IS 'EMAIL DE USUARIO',
  PASSWORD  IS 'PASSWORD ENCRIPTADO'
);

LABEL ON COLUMN JOMUMA1.USUARIOS_SISTEMA ( 
  ID        TEXT IS 'ID',
  NOMBRE    TEXT IS 'NOMBRE DE USUARIO',
  APELLIDOS TEXT IS 'APELLIDOS DE USUARIO',
  EMAIL     TEXT IS 'EMAIL DE USUARIO',
  PASSWORD  TEXT IS 'PASSWORD ENCRIPTADO'
);
